#[derive(Default, Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct MeResponse {
  pub awardee_karma: i64,
  pub awarder_karma: i64,
  pub can_create_subreddit: bool,
  pub can_edit_name: bool,
  pub coins: i64,
  pub comment_karma: i64,
  pub created: f64,
  pub created_utc: f64,
  pub force_password_reset: bool,
  pub gold_creddits: i64,
  pub gold_expiration: ::serde_json::Value,
  pub has_android_subscription: bool,
  pub has_external_account: bool,
  pub has_gold_subscription: bool,
  pub has_ios_subscription: bool,
  pub has_paypal_subscription: bool,
  pub has_stripe_subscription: bool,
  pub has_subscribed: bool,
  pub has_subscribed_to_premium: bool,
  pub has_verified_email: bool,
  pub has_visited_new_profile: bool,
  pub hide_from_robots: bool,
  pub icon_img: String,
  pub id: String,
  pub in_beta: bool,
  pub in_redesign_beta: bool,
  pub inbox_count: i64,
  pub is_employee: bool,
  pub is_gold: bool,
  pub is_mod: bool,
  pub is_sponsor: bool,
  pub is_suspended: bool,
  pub link_karma: i64,
  pub linked_identities: Vec<::serde_json::Value>,
  pub name: String,
  pub num_friends: i64,
  pub oauth_client_id: String,
  pub over18: Option<bool>,
  pub password_set: bool,
  pub pref_autoplay: bool,
  pub pref_clickgadget: i64,
  pub pref_geopopular: String,
  pub pref_nightmode: bool,
  pub pref_no_profanity: bool,
  pub pref_show_snoovatar: bool,
  pub pref_show_trending: bool,
  pub pref_show_twitter: bool,
  pub pref_top_karma_subreddits: bool,
  pub pref_video_autoplay: bool,
  pub seen_give_award_tooltip: bool,
  pub seen_layout_switch: bool,
  pub seen_premium_adblock_modal: bool,
  pub seen_redesign_modal: bool,
  pub seen_subreddit_chat_ftux: bool,
  pub suspension_expiration_utc: ::serde_json::Value,
  pub total_karma: i64,
  pub verified: bool,
}

#[derive(Default, Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct MeKarmaResponse {
    pub kind: String,
    pub data: Vec<::serde_json::Value>,
}

#[derive(Default, Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct MePrefsResponse {
    pub accept_pms: String,
    pub activity_relevant_ads: bool,
    pub allow_clicktracking: bool,
    pub beta: bool,
    pub clickgadget: bool,
    pub collapse_left_bar: bool,
    pub collapse_read_messages: bool,
    pub compress: bool,
    pub default_comment_sort: String,
    pub default_theme_sr: ::serde_json::Value,
    pub design_beta: bool,
    pub domain_details: bool,
    pub email_digests: bool,
    pub email_messages: bool,
    pub email_unsubscribe_all: bool,
    pub enable_default_themes: bool,
    pub geopopular: String,
    pub hide_ads: bool,
    pub hide_downs: bool,
    pub hide_from_robots: bool,
    pub hide_ups: bool,
    pub highlight_controversial: bool,
    pub highlight_new_comments: bool,
    pub ignore_suggested_sort: bool,
    pub label_nsfw: bool,
    pub lang: String,
    pub layout: i64,
    pub legacy_search: bool,
    pub live_orangereds: bool,
    pub mark_messages_read: bool,
    pub media: String,
    pub media_preview: String,
    pub min_comment_score: i64,
    pub min_link_score: i64,
    pub monitor_mentions: bool,
    pub newwindow: bool,
    pub nightmode: bool,
    pub no_profanity: bool,
    pub num_comments: i64,
    pub numsites: i64,
    pub over18: Option<bool>,
    pub private_feeds: bool,
    pub profile_opt_out: bool,
    pub public_server_seconds: bool,
    pub public_votes: bool,
    pub research: bool,
    pub search_include_over18: Option<bool>,
    pub send_crosspost_messages: bool,
    pub send_welcome_messages: bool,
    pub show_flair: bool,
    pub show_gold_expiration: bool,
    pub show_link_flair: bool,
    pub show_location_based_recommendations: bool,
    pub show_snoovatar: bool,
    pub show_stylesheets: bool,
    pub show_trending: bool,
    pub show_twitter: bool,
    pub store_visits: bool,
    pub survey_last_seen_time: ::serde_json::Value,
    pub third_party_data_personalized_ads: bool,
    pub third_party_site_data_personalized_ads: bool,
    pub third_party_site_data_personalized_content: bool,
    pub threaded_messages: bool,
    pub threaded_modmail: bool,
    pub top_karma_subreddits: bool,
    pub use_global_defaults: bool,
    pub video_autoplay: bool,
}

#[derive(Default, Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PrefsFriendsResponse {
    pub data: PrefsFriendsResponseData,
    pub kind: String,
}

#[derive(Default, Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PrefsFriendsResponseData {
    pub children: Vec<::serde_json::Value>,
}
